server:
  run-mode:
  # 服务端口配置：
  # - 格式：-ip:port (指定监听的IP地址)
  # - 格式：:port (监听所有可用接口)
  http-port: :8000
  read-timeout: 60 # 等待客户端发送数据的最大时间（以秒为单位）
  write-timeout: 60 # 等待服务端发送响应的最大时间（以秒为单位）
  # 用于监控服务器性能的接口（适合内部调试使用）
  private-http-listen: :8001

security:
  # API请求的授权令牌（用于验证客户端身份）
  auth-token: 6666

app:
  default-page-size: 10 # 分页API每页默认返回的项目数量
  max-page-size: 100 # 分页API每页允许的最大项目数量
  default-context-timeout: 60 # API请求的默认超时时间（以秒为单位）
  log-save-path: storage/logs # 应用日志的保存目录
  log-file: app.log # 日志文件的名称

  temp-path: storage/temp # 用于临时处理文件的目录
  # API返回的上传文件URL的前缀
  upload-url-pre: https://image.diybeta.com
  # 上传文件的最大允许大小，单位为MB
  upload-max-size: 5
  # 允许上传的文件类型（根据文件扩展名）
  upload-allow-exts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif
    - .tiff
    - .avif
    - .webp
  # 上传图片尺寸限制-宽度
  image-max-size-width: 500
  # 上传图片尺寸限制-高度
  image-max-size-height: 500
  # 上传图片质量 0-100 区间
  image-quality: 500

# 本地文件存储配置
local-fs:
  enable: true # 是否启用本地文件存储
  # 启用一个内部HTTP文件访问服务以访问本地存储的文件
  httpfs-enable: true
  # 上传文件的保存目录
  save-path: storage/uploads

# 阿里云 OSS（对象存储服务）的配置
oss:
  enable: false # 是否启用OSS云存储
  endpoint: # OSS的终端地址（例如：oss-cn-beijing.aliyuncs.com）
  bucket-name: # OSS存储桶名称
  access-key-id: # OSS的访问密钥ID
  access-key-secret: # OSS的访问密钥Secret
  # 在OSS中保存文件的自定义目录前缀
  custom-path: blog

# Cloudflare R2存储的配置
cloudflu-r2:
  enable: false # 是否启用Cloudflare R2存储
  bucket-name: image # R2存储桶名称
  account-id: # Cloudflare账号ID
  access-key-id: # R2访问密钥ID
  access-key-secret: # R2访问密钥Secret
  # 在R2中保存文件的自定义目录前缀
  custom-path: blog

# 亚马逊S3存储的配置
aws-s3:
  enable: false # 是否启用AWS S3云存储
  region: # AWS区域（例如：us-west-1）
  bucket-name: # S3存储桶名称
  access-key-id: # AWS访问密钥ID
  access-key-secret: # AWS访问密钥Secret
  # 在S3中保存文件的自定义目录前缀
  custom-path: blog

# 用于发送错误报告的电子邮件配置
email:
  error-report-enable: false # 是否启用通过电子邮件发送错误报告
  host: smtp.gmail.com # SMTP服务器地址
  port: 465 # SMTP服务器端口
  user-name: xxx # 邮件账户用户名
  password: xxx # 邮件账户密码
  is-ssl: true # 是否使用SSL连接
  from: xxx # 发件人电子邮件地址
  to: # 收件人电子邮件地址列表
    - xxx
