Server:
  RunMode: debug
  # 服务端口 格式为 IP:PORT (注定监听IP) 或者 :PORT (监听所有)
  HttpPort:  :8000
  ReadTimeout: 60
  WriteTimeout: 60
  # 性能监听接口
  PrivateHttpListen:  :8001
Security:
  # 图片上传API授权TOKEN
  AuthToken: 6666
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  # 图片文件存储地址
  UploadSavePath: storage/uploads
  # 上传附件访问地址,需要包含 UploadSavePath, 这里用来描述接口返回给上传端使用的URL前缀
  UploadServerUrl: http://127.0.0.1:8000/storage/uploads
  # 上传大小限制 单位MB
  UploadImageMaxSize: 5
  # 上传图片类型限制
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif
    - .svg
    - .tiff
# 阿里云OSS
OSS:
  # 是否开启OSS云存储
  Enable: false
  BucketName:
  Endpoint:
  AccessKeyID:
  AccessKeySecret:

Email:
  Host: smtp.gmail.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx