Server:
  RunMode: debug
  #服务端口
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
  #性能监听接口
  PrivateHttpListen: 8001
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  # 上传附件访问地址
  UploadServerUrl: http://127.0.0.1:8000/storage/uploads
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Security:
  AuthToken: 6666
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
OSS:
  BucketName:
  AccessURLDomain: https://.com/
  Endpoint:
  AccessKeyID:
  AccessKeySecret :