// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/client/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取客户端版本信息",
                "parameters": [
                    {
                        "maxLength": 100,
                        "type": "string",
                        "description": "标签名称",
                        "name": "platform",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "default": 1,
                        "description": "状态",
                        "name": "versionCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/service.ClientVersion"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ErrResult": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码"
                },
                "data": {
                    "description": "错误格式数据"
                },
                "details": {
                    "description": "错误支付"
                },
                "msg": {
                    "description": "失败\u0026\u0026成功消息"
                },
                "status": {
                    "description": "业务状态码"
                }
            }
        },
        "app.ListRes": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "数据清单"
                },
                "pager": {
                    "description": "翻页信息",
                    "$ref": "#/definitions/app.Pager"
                }
            }
        },
        "app.Pager": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "totalRows": {
                    "description": "总行数",
                    "type": "integer"
                }
            }
        },
        "app.ResListResult": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码"
                },
                "data": {
                    "description": "数据集合",
                    "$ref": "#/definitions/app.ListRes"
                },
                "msg": {
                    "description": "失败\u0026\u0026成功消息"
                },
                "status": {
                    "description": "业务状态码"
                }
            }
        },
        "service.ClientVersion": {
            "type": "object",
            "properties": {
                "ID": {
                    "description": "用户id",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "details": {
                    "description": "版本更新详情",
                    "type": "string"
                },
                "platform": {
                    "description": "平台 1:安卓 2:ios",
                    "type": "integer"
                },
                "resourceURL": {
                    "description": "版本更新资源地址",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "versionCode": {
                    "description": "版本号",
                    "type": "integer"
                },
                "versionName": {
                    "description": "版本名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
