# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: obsidian-image-api-gateway
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Set Time
      run: |
        TIME="$(TZ='Asia/Shanghai' date +'%FT%T%z')"
        echo "TIME=$TIME" >> $GITHUB_ENV

    - name: Get Tag Version
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV


    - name: Get version1
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo Version
      run: echo ${{ env.GIT_TAG }}   ${{ env.TIME }} ${{ steps.get_version.outputs.VERSION }} ${{ github.ref_name }}