# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: obsidian-image-api-gateway
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Set Time
      run: |
        TIME="$(TZ='Asia/Shanghai' date +'%FT%T%z')"
        echo "TIME=$TIME" >> $GITHUB_ENV

    - name: Get Tag Version
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs/tags/*}" >> $GITHUB_ENV

    - name: build-linux
      run: |
        echo ${{ env.RELEASE_VERSION }}   ${{ env.TIME }}
    - name: Get version1
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo Version
      run: echo ${{ steps.get_version.outputs.VERSION }}