# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: obsidian-image-api-gateway
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set Time1
      run: |
        TIME="$(TZ='Asia/Shanghai' date +'%FT%T%z')"
        echo "TIME=$TIME" >> $GITHUB_ENV

    - name: Set Time
      run: echo "TIME2=`echo $(TZ='Asia/Shanghai' date +'%FT%T%z')`" >> $GITHUB_ENV
    - name: Get Tag Version
      run: echo "TAG_VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
    - name: Echo Version
      run: echo ${{ env.TAG_VERSION }} ${{ env.TIME }}${{ env.TIME2 }}